site_name: Labridge
repo_url: https://github.com/scramblingsnail/Labridge
repo_name: Labridge
copyright: Copyright &copy; 2024 A-Duiduidui Team.

nav:
  - Home: index.md
  - Function Module:
      - Papers:
          - function_modules/paper/index.md
          - Shared papers:
              - function_modules/paper/shared_papers/index.md
              - function_modules/paper/shared_papers/parse.md
              - function_modules/paper/shared_papers/store.md
              - function_modules/paper/shared_papers/retrieve.md
          - Personal recent papers:
              - function_modules/paper/temporary_papers/index.md
              - function_modules/paper/temporary_papers/store.md
              - function_modules/paper/temporary_papers/retrieve.md
              - Download:
                  - function_modules/paper/temporary_papers/download/arXiv.md
      - Chat history:
          - function_modules/chat_history/index.md
          - function_modules/chat_history/short-term_history.md
          - Long-term history:
              - function_modules/chat_history/long-term_history/store.md
              - function_modules/chat_history/long-term_history/retrieve.md
      - Experiment logs:
          - function_modules/experiment_log/index.md
          - Personal experiment logs:
              - function_modules/experiment_log/personal_experiment/index.md
              - function_modules/experiment_log/personal_experiment/store.md
              - function_modules/experiment_log/personal_experiment/retrieve.md
          - Shared experiment logs:
              - function_modules/experiment_log/shared_experiment/index.md
      - Instruments:
          - function_modules/instrument/index.md
          - Store: function_modules/instrument/store.md
          - Retrieve: function_modules/instrument/retrieve.md
      - References:
          - function_modules/reference/index.md
          - function_modules/reference/instrument_reference.md
          - function_modules/reference/paper_reference.md
  - Agent & Tools:
      - agent_tools/prompt_framework.md
      - Tools:
          - agent_tools/tools/index.md
          - Base:
              - agent_tools/tools/base/tool_base.md
              - agent_tools/tools/base/tool_log.md
          - Chat history:
              - agent_tools/tools/chat_history/chat_memory_retrieve_tool.md
          - Experiment log:
              - agent_tools/tools/experiment_log/create_new_experiment_log.md
              - agent_tools/tools/experiment_log/experiment_log_retrieve_tool.md
              - agent_tools/tools/experiment_log/record_experiment_log_tool.md
              - agent_tools/tools/experiment_log/set_current_experiment_tool.md
          - Interact:
              - agent_tools/tools/interact/collect_and_authorize_tool.md
          - Shared papers:
              - agent_tools/tools/shared_papers/shared_paper_retrieve_tool.md
          - Temporary papers:
              - agent_tools/tools/temporary_papers/add_new_recent_paper_tool.md
              - agent_tools/tools/temporary_papers/arxiv_search_download_tool.md
              - agent_tools/tools/temporary_papers/recent_paper_retrieve_tool.md
              - agent_tools/tools/temporary_papers/recent_paper_summarize_tool.md
  - Deployment:
      - deployment/index.md
      - deployment/software.md
      - deployment/hardware.md
  - User Interface:
      - interface/index.md
      - Server-Client: interface/server-client.md
      - Android APP: interface/android_app.md
      - Web UI: interface/web_ui.md
  - Demonstration:
      - demonstration/index.md
      - Experiment logs:
          - demonstration/experiment_log/record_log.md
          - demonstration/experiment_log/retrieve_log.md
      - Instrument:
          - demonstration/instrument/instrument_docs.md
          - demonstration/instrument/instrument_operations.md
      - Paper:
          - demonstration/paper/paper_download.md
          - demonstration/paper/recent_papers_qa.md
          - demonstration/paper/shared_papers.md
  - Code Docs:
#      - code_docs/index.md
      - Accounts:
          - code_docs/accounts/super_users.md
          - code_docs/accounts/users.md
      - Agent:
          - code_docs/agent/chat_agent.md
          - Chat Msg:
              - code_docs/agent/chat_msg/msg_types.md
          - ReAct:
              - code_docs/agent/react/prompt.md
              - code_docs/agent/react/react.md
              - code_docs/agent/react/react_chat_format.md
              - code_docs/agent/react/react_step.md
      - Callback:
          - Base:
              - code_docs/callback/base/operation_base.md
              - code_docs/callback/base/operation_log.md
          - Experiment_log:
              - code_docs/callback/experiment_log/new_experiment.md
              - code_docs/callback/experiment_log/set_current_experiment.md
          - Paper:
              - code_docs/callback/paper/add_recent_paper.md
              - code_docs/callback/paper/paper_download.md
              - code_docs/callback/paper/paper_summarize.md
      - Common:
          - Prompt:
              - code_docs/common/prompt/llm_doc_choice_select.md
          - Query_engine:
              - code_docs/common/query_engine/query_engines.md
          - Utils:
              - code_docs/common/utils/chat.md
              - code_docs/common/utils/time.md
      - Func_modules:
          - Instrument:
              - Prompt:
                  - code_docs/func_modules/instrument/prompt/llm_instrument_choice_select.md
              - Retrieve:
                  - code_docs/func_modules/instrument/retrieve/instrument_retriever.md
              - Store:
                  - code_docs/func_modules/instrument/store/instrument_store.md
          - Memory:
              - code_docs/func_modules/memory/base.md
              - Chat:
                  - code_docs/func_modules/memory/chat/chat_memory.md
                  - code_docs/func_modules/memory/chat/retrieve.md
                  - code_docs/func_modules/memory/chat/short_memory.md
              - Experiment:
                  - code_docs/func_modules/memory/experiment/experiment_log.md
                  - code_docs/func_modules/memory/experiment/retrieve_log.md
          - Paper:
              - Download:
                  - code_docs/func_modules/paper/download/arxiv.md
                  - code_docs/func_modules/paper/download/async_utils.md
              - Parse:
                  - code_docs/func_modules/paper/parse/paper_reader.md
                  - Extractors:
                      - code_docs/func_modules/paper/parse/extractors/metadata_extract.md
                      - code_docs/func_modules/paper/parse/extractors/source_analyze.md
                  - Parsers:
                      - code_docs/func_modules/paper/parse/parsers/auto.md
                      - code_docs/func_modules/paper/parse/parsers/base.md
                      - code_docs/func_modules/paper/parse/parsers/default_parser.md
                      - code_docs/func_modules/paper/parse/parsers/ieee_parser.md
                      - code_docs/func_modules/paper/parse/parsers/nature_parser.md
              - Prompt:
                  - Store:
                      - code_docs/func_modules/paper/prompt/store/dir_summary.md
                  - Synthesize:
                      - code_docs/func_modules/paper/prompt/synthesize/paper_summarize.md
                      - code_docs/func_modules/paper/prompt/synthesize/synthesize.md
              - Retrieve:
                  - code_docs/func_modules/paper/retrieve/paper_retriever.md
                  - code_docs/func_modules/paper/retrieve/temporary_paper_retriever.md
              - Store:
                  - code_docs/func_modules/paper/store/paper_store.md
                  - code_docs/func_modules/paper/store/temporary_store.md
              - Synthesizer:
                  - code_docs/func_modules/paper/synthesizer/summarize.md
          - Reference:
              - code_docs/func_modules/reference/base.md
              - code_docs/func_modules/reference/instrument.md
              - code_docs/func_modules/reference/paper.md
      - Interact:
          - Authorize:
              - code_docs/interact/authorize/authorize.md
          - Collect:
              - Collector:
                  - code_docs/interact/collect/collector/common_collector.md
                  - code_docs/interact/collect/collector/select_collector.md
              - Manager:
                  - code_docs/interact/collect/manager/collect_manager.md
              - Types:
                  - code_docs/interact/collect/types/common_info.md
                  - code_docs/interact/collect/types/info_base.md
                  - code_docs/interact/collect/types/select_info.md
              - code_docs/interact/collect/pipeline.md
              - code_docs/interact/collect/utils.md
      - Interface:
          - code_docs/interface/http_server.md
          - code_docs/interface/utils.md
      - Models:
          - Local:
              - code_docs/models/local/mindspore_models.md
          - Remote:
              - code_docs/models/remote/remote_models.md
              - code_docs/models/remote/remote_server.md
      - Tools:
          - Base:
              - code_docs/tools/base/function_base_tools.md
              - code_docs/tools/base/tool_base.md
              - code_docs/tools/base/tool_log.md
          - Common:
              - code_docs/tools/common/date_time.md
          - Instrument:
              - code_docs/tools/instrument/retrieve.md
          - Interact:
              - code_docs/tools/interact/collect_and_authorize.md
          - Memory:
              - Chat:
                  - code_docs/tools/memory/chat/retrieve.md
              - Experiment:
                  - code_docs/tools/memory/experiment/insert.md
                  - code_docs/tools/memory/experiment/retrieve.md
          - Paper:
              - Download:
                  - code_docs/tools/paper/download/arxiv_download.md
              - Shared_papers:
                  - code_docs/tools/paper/shared_papers/query.md
                  - code_docs/tools/paper/shared_papers/retriever.md
                  - code_docs/tools/paper/shared_papers/utils.md
              - Temporary_papers:
                  - code_docs/tools/paper/temporary_papers/insert.md
                  - code_docs/tools/paper/temporary_papers/paper_retriever.md
                  - code_docs/tools/paper/temporary_papers/paper_summarize.md
          - code_docs/tools/utils.md


theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    # - navigation.instant  # see https://github.com/ultrabug/mkdocs-static-i18n/issues/62
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.path
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
    - content.action.view
    - content.action.edit
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.code.annotations
  favicon: assets/favicon.ico
  icon:
    logo: logo

markdown_extensions:
  # Officially Supported Extensions
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - sane_lists
  - tables
  - toc:
      permalink: true
  - wikilinks
  # Third Party Extensions(Bundles, PyMdown Extensions)
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            # Headings
            show_root_heading: true
            show_root_toc_entry: true
            show_object_full_path: true
            # Members
            show_submodules: false
            # Docstrings
            docstring_section_style: spacy
  - with-pdf:
      verbose: True
      author: zhisan
      copyright: A-Duiduiduidui Team


  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - locale: en
          default: false
          name: English
        - locale: zh
          default: true
          name: 中文
          nav_translations:
            Home: 主页
            Function Module: 功能模块
            User Interface: 用户界面
            Code Docs: 源码文档
            Agent & Tools: Agent与可用工具
            Deployment: 项目部署
            Demonstration: 应用展示